services:
  webserver:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 192.168.2.248:80:80
      - 192.168.2.248:81:81
      - 192.168.2.248:443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
      
  testwebserver:
    image: localhost:5000/marcel0024/testwebserver:latest
    container_name: testwebserver
    labels: [ "com.centurylinklabs.watchtower.scope=local" ]
    restart: unless-stopped    
    ports:
      - 5100:8080