services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    hostname: Nuc
    environment:
      - TZ=Europe/Amsterdam
      - PLEX_CLAIM=$PLEX_CLAIM
      - ALLOWED_NETWORKS=$ALLOWED_NETWORKS
      - ADVERTISE_IP=$ADVERTISE_IP
    volumes:
      - plex_config:/config
      - plex_transcode:/transcode
      - $MEDIA_LOCATION:/data
    ports:
      - "32400:32400/tcp"
      - "32469:32469/tcp"
    devices:
     - /dev/dri:/dev/dri 
    restart: always
    
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - kavita_config:/config
      - $MEDIA_LOCATION/books:/data
    ports:
      - "192.168.2.246:80:5000"
    restart: unless-stopped

volumes:
  plex_config:
  plex_transcode:
  kavita_config:
  
