services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    hostname: Nuc
    environment:
      - TZ=Europe/Amsterdam
      - PLEX_CLAIM=$PLEX_CLAIM
      - ALLOWED_NETWORKS=$ALLOWED_NETWORKS
      - ADVERTISE_IP=$ADVERTISE_IP
    volumes:
      - plex_config:/config
      - plex_transcode:/transcode
      - $MEDIA_LOCATION:/data
    ports:
      - "32400:32400/tcp"
      - "32469:32469/tcp"
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "109"
    restart: always

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - type: bind
        source: $MEDIA_LOCATION/movies
        target: /movies
      - type: bind
        source: $MEDIA_LOCATION/tv
        target: /tv
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://jelly.local
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    group_add:
      - "109"
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  plex_config:
  plex_transcode:
  kavita_config:
  jellyfin_config:
  jellyfin_cache:


