services:
  meilisearch:
    image: getmeili/meilisearch:v1.4 # 
    container_name: meilisearch
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - meilisearch_data:/meili_data

  redis:
    image: redis
    container_name: redis_recipes
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  bar-assistant:
    image: barassistant/server:v3
    container_name: bar-assistant
    depends_on:
      meilisearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # - PUID=1000 # Optional
      # - PGID=1000 # Optional
      - APP_URL=$API_URL
      - LOG_CHANNEL=stderr # 
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=http://meilisearch:7700 # 
      - REDIS_HOST=redis # 
      - ALLOW_REGISTRATION=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - bar_data:/var/www/cocktails/storage/bar-assistant
      
  salt-rim:
    image: barassistant/salt-rim:v2
    container_name: salt-rim
    depends_on:
      bar-assistant:
        condition: service_healthy
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
      - BAR_NAME=$BAR_NAME
      - DESCRIPTION=$BAR_DESCRIPTION
      - DEFAULT_LOCALE=en-US
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  webserver:
    image: nginx:alpine
    container_name: bar_web
    restart: unless-stopped
    depends_on:
      bar-assistant:
        condition: service_healthy
      salt-rim:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    ports:
      - 3000:3000 # 
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # 
      
volumes:
  bar_data:
  meilisearch_data: