services:
  portainer:
    image: portainer/portainer-ce
    network_mode: bridge
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      
  glances:
    image: nicolargo/glances
    container_name: glances
    restart: always
    hostname: Nuc
    ports:
      - "192.168.2.249:80:61208"
    environment:
      - TZ=Europe/Amsterdam
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
    pid: host
    
  watchtower:
    image: ghcr.io/containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCOPE=none
      - WATCHTOWER_SCHEDULE=0 0 6 * * *
      - WATCHTOWER_INCLUDE_STOPPED=true
      - TZ=Europe/Amsterdam
        
  watchtower_local:
    image: ghcr.io/containrrr/watchtower:latest
    container_name: watchtower-local 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_SCOPE=local
      - WATCHTOWER_INCLUDE_STOPPED=true
      - TZ=Europe/Amsterdam
       

volumes:
  portainer_data: