version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce
    network_mode: bridge
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 6 * * *
      - TZ=Europe/Amsterdam

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    hostname: Nuc
    ports:
      - "192.168.2.249:80:61208"
    environment:
      - TZ=Europe/Amsterdam
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
    pid: host

volumes:
  portainer_data:
