services:
  portainer:
    image: portainer/portainer-ce
    network_mode: bridge
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: always
    hostname: Nuc
    ports:
      - "192.168.2.249:80:61208"
    environment:
      - TZ=urope/Brussels
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
    pid: host

  watchtower:
    image: ghcr.io/containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCOPE=none
      - WATCHTOWER_SCHEDULE=0 0 8 * * 6,0
      - WATCHTOWER_INCLUDE_STOPPED=true
      - TZ=Europe/Brussels

volumes:
  portainer_data: