version: '3.9'

services:
  azure-build-agent1:
    container_name: azure-build-agent1
    build:
      context: ~/apps/azure-build-agent
      dockerfile: agent.dockerfile
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
    environment:
      - AZP_URL=$AZP_URL
      - AZP_TOKEN=$AZP_TOKEN
      - AZP_AGENT_NAME=$AZP_AGENT_NAME Container 1
      - AZP_POOL=$AZP_POOL

  azure-build-agent2:
    container_name: azure-build-agent2
    build:
      context: ~/apps/azure-build-agent
      dockerfile: agent.dockerfile
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
    environment:
      - AZP_URL=$AZP_URL
      - AZP_TOKEN=$AZP_TOKEN
      - AZP_AGENT_NAME=$AZP_AGENT_NAME Container 2
      - AZP_POOL=$AZP_POOL
