services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          cpus: "6"
    restart: unless-stopped

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - TZ=Europe/Amsterdam
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "192.168.2.248:80:8080"
    restart: unless-stopped  

volumes:
  ollama:
  open-webui: