version: '3.8'

services:
  unbound:
    container_name: unbound
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    image: pedantic/unbound:latest
    volumes:
     - unbound:/opt/unbound/etc/unbound
    ports:
     - "192.168.2.252:53:53/udp"
     - "192.168.2.252:53:53/tcp"
    restart: always
    
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - TZ=Europe/Amsterdam
      - FTLCONF_LOCAL_IPV4=192.168.2.253
      - WEBPASSWORD=$WEBPASSWORD
      - IPv6=False
      - WEB_PORT=80
      - PIHOLE_DNS_=192.168.2.252
    volumes:
      - pihole:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    ports:
      - "192.168.2.253:53:53/tcp"
      - "192.168.2.253:53:53/udp"
      - "192.168.2.253:80:80/tcp"
    restart: always
    depends_on:
      - unbound
    
volumes:
  pihole:
  pihole_dnsmasq: 
  unbound:


