services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: Nuc
    environment:
      - TZ=Europe/Amsterdam
      - FTLCONF_LOCAL_IPV4=192.168.2.253
      - WEBPASSWORD=$WEBPASSWORD
      - WEB_PORT=80
      - PIHOLE_DNS_=192.168.2.252
      - FTL_CMD=no-daemon -- --dns-forward-max 300
    volumes:
      - pihole:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    ports:
      - "192.168.2.253:53:53/tcp"
      - "192.168.2.253:53:53/udp"
      - "192.168.2.253:80:80/tcp"
    restart: always

  unbound:
    container_name: unbound
    image: pedantic/unbound:latest
    volumes:
      - unbound:/opt/unbound/etc/unbound
    ports:
      - "192.168.2.252:53:53/udp"
      - "192.168.2.252:53:53/tcp"
    restart: always

volumes:
  pihole:
  pihole_dnsmasq:
  unbound:


