version: '3.9'

services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    restart: always
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Europe/Amsterdam
      - TS_AUTHKEY=$TAILSCALE_AUTHKEY
      - TS_AUTH_ONCE=true
      - TS_ROUTES=192.168.2.0/24
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
      - /var/lib/tailscale:/var/lib/tailscale

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=openvpn
      - OPENVPN_USER=$OPENVPN_USER
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - SERVER_REGIONS=Netherlands,Belgium
    restart: always
    ports:
      # qbittorrent
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      # prowlarr
      - 9696:9696
      # radarr
      - 7878:7878
      # sonarr
      - 8989:8989
