services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Europe/Amsterdam
      - TS_AUTHKEY=$TAILSCALE_AUTHKEY
      - TS_ROUTES=192.168.2.0/24
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
      - tailscaledata:/var/lib/tailscale

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Brussels
      - VPN_TYPE=wireguard
      - VPN_SERVICE_PROVIDER=windscribe
      - WIREGUARD_PRIVATE_KEY=$WINDSCRIBE_PRIVATEKEY
      - WIREGUARD_ADDRESSES=$WINDSCRIBE_ADDRESSES
      - WIREGUARD_PRESHARED_KEY=$WINDSCRIBE_PRESHAREDKEY
      - WIREGUARD_ENDPOINT_PORT=65142
      - SERVER_REGIONS=Netherlands,Belgium
    restart: always
    ports:
      # sabnzbd
      - "8080:8080"
      # qbittorrent
      - "8081:8081"
      - "6881:6881"
      - "6881:6881/udp"
      # prowlarr
      - "9696:9696"
      # radarr
      - "7878:7878"
      # sonarr
      - "8989:8989"
      # overseerr
      - "192.168.2.250:80:5055"

volumes:
  tailscaledata:
