# all ports of the services are via Gluetun. Ports are defined in ../vpn

services:
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - HAS_IPV6=false
    volumes:
      - sabnzbd_config:/config
      - $MEDIA_LOCATION/usenet:/config/Downloads/complete
      - $MEDIA_LOCATION/usenet/incomplete:/config/Downloads/incomplete
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "container:gluetun"
    environment:
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8081
      - PUID=1000
      - PGID=1000
    volumes:
      - qbittorrent_config:/config
      - $MEDIA_LOCATION/torrents:/downloads
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "container:gluetun"
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
    volumes:
      - prowlarr_config:/config
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - radarr_config:/config
      - radarr_downloads:/downloads
      - $MEDIA_LOCATION:/movies
    depends_on:
      - prowlarr
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: "container:gluetun"
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
    volumes:
      - sonarr_config:/config
      - sonarr_downloads:/downloads
      - $MEDIA_LOCATION:/tv
    depends_on:
      - prowlarr
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr
    container_name: overseerr
    network_mode: "container:gluetun"
    environment:
      - TZ=Europe/Amsterdam
      - PORT=5055
    volumes:
      - overseerr_config:/app/config
    restart: unless-stopped

volumes:
  qbittorrent_config:
  prowlarr_config:
  radarr_config:
  radarr_downloads:
  sonarr_config:
  sonarr_downloads:
  readarr_config:
  readarr_books:
  overseerr_config:
  sabnzbd_config:
