version: '3.9'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - "192.168.2.251:80:8123"
    restart: unless-stopped

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./mosquitto-data/conf:/mosquitto/conf
      - ./mosquitto-data/data:/mosquitto/data
      - ./mosquitto-data/log:/mosquitto/log
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"
    depends_on:
      - homeassistant

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.34.0
    volumes:
      - ./zigbee2mqtt-data:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "8124:8124"
      - "8125:8080"
    restart: unless-stopped
    depends_on:
      - mosquitto

volumes:
  homeassistant_config:
