services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8066:8081"
    volumes:
      - /home/marcel/data/media/youtube:/downloads