services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: pdf
    ports:
      - 192.168.2.248:80:8080
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: $DOMAIN
      SIGNUPS_ALLOWED: false
    volumes:
      - vaultwarden:/data/
    ports:
      - 5058:80

volumes:
  vaultwarden:      